dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: QwMWmX8WEJzbn4pz3vL00wAR5o6WHdJe1qtPsB9VNfCNjr3Q8ovWXOtLf5eaA3GYUnjtiIwkdW0BUX0dJSznM+ll4DV+7ftioHjZYpHpdQNCT4EuuUAqYIVmM+tS+gb+xNAygol3o3K/59LdKlvn7o2Ekr5J2Ca8YYF/BdGKYVnBDWRkyItXl7cEcHMuL15seZVUCCcaDcubVLElqKnHu5oJ2UcHHyGvViRXJ11y0EMDQ4JtABb2G0PUdptK4rGaoPJVdFnbdrfLXbeFzXOjYtJZhyo23rVteHy4TSHmnh6UE6poq0keTdAuHguF3poXhKKIlGAXroirPrenOp9ISB5y/zwPdNthbr6hTdfjIs+JxifUo0H9UuRxh9r5gP4HEMaiwsmxpUxrsosDON8aT95Vi2vEhlmCpwF8Wju0eP6wiKufeUW78SP83TudrsFuX3gHnM/fUVV/uztVXk2p/eLw7v7ziqMR06e6D+Wv5MMfBqCf0kPJZRNBS7eEY2lKrzMoriw+on3ucgf28DqSnqRbVVHqk9Y5Wxy5hjpKU5GKIHmIJgchuYkWEykTmG2F6z/zAES2HYrWmU4qlQWGa0lV6XjDGFhDSIhhPwbtnJzKoGxAJfFOSSnl2HNOTgFkwA3nENV1RiGG0uMynIpXzB0LiozBOeewkpjkV4jQS4U=
