---
- name: install mogod
  hosts: all
  become: true
  tasks:
  - name: Add APT key
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com

  - name: add repo to /apt/source.list
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present
  - name: Install mongodb package
    apt:
      name: mongodb-org
      state: present
  - name: start mongo
    systemd:
      name: mongod
      enabled: yes


